import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
import { SessionProvider } from "next-auth/react";
import AuthComponent from "@/components/AuthComponent";
import SignOutButton from "@/components/signout";
import Link from "next/link";

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SessionProvider>
					<div className="flex flex-col items-center text-center h-screen p-5">
						<Link href="/" className="flex-none p-2">
							<h1 className="text-4xl text-center text-primary font-bold transition duration-200 ease-in-out hover:scale-105 ">Workout Tracker</h1>
						</Link>
						<AuthComponent>{children}</AuthComponent>
					</div>
				</SessionProvider>
			</body>
		</html>
	);
}
